version: 2

models:
  - name: dim_location
    description: "dimension describing different city and country pairs where tournaments held in Djookovic titles dataset."
    columns: 
      - name: location_key
        tests: 
          - not_null
          - unique
      
      - name: location
        description: "City where tournament held"
        tests: 
          - not_null

  - name: dim_surface
    description: "Court surface types used in Djokovic titles dataset"
    columns: 
      - name: surface_key
        tests: 
          - not_null
          - unique

      - name: Surface
        description: "Type of tennis court surface (Clay, Grass, Hard or Indoor)"
        tests: 
          - not_null

  - name: dim_opponent
    description: "dimension detailing the opponents faced in each tournament final in Djookovic titles dataset"
    columns: 
      - name: opponent_key
        tests:
          - not_null
          - unique

      - name: Final_Opponent
        description: "name of opponent faced in Final of tournament"
        tests: 
          - not_null

  - name: dim_atp_level
    description: "dimension containing the tournament level types used in Djokovic titles dataset"
    columns: 
      - name: atp_level_key
        tests: 
          - not_null
          - unique

      - name: atp_level_raw
        description: "level of ATP tournament"
        tests:
          - not_null

  - name: dim_tournament
    description: "dimension containing the names of all the tournaments used in Djokovic titles dataset"
    columns: 
      - name: tournament_key
        tests: 
          - not_null
          - unique

      - name: Tournament
        description: "names of each tournament appearing in Djokovic titles dataset"
        tests:
          - not_null

  